"""
Vectorization Service using VTracer

VTracer is the fastest, highest quality open-source vectorizer.
- Matches Adobe Illustrator quality
- 1-3 second processing time
- Released by VisionCortex
- License: MIT (commercial use allowed)

Source: https://github.com/visioncortex/vtracer
"""

import vtracer
import numpy as np
from PIL import Image
import time
from typing import Optional

from utils.logger import logger


class VectorizerService:
    """
    Service for vectorizing images using VTracer
    """
    
    def __init__(self):
        """Initialize the vectorizer service"""
        self.default_config = {
            'colormode': 'color',        # Full color support
            'hierarchical': 'stacked',   # Best for print graphics
            'mode': 'spline',            # Smooth curves
            'filter_speckle': 4,         # Remove noise
            'color_precision': 6,        # Good color accuracy
            'layer_difference': 16,      # Separate colors well
            'corner_threshold': 60,      # Balance detail vs smoothness
            'length_threshold': 4.0,     # Remove tiny segments
            'splice_threshold': 45,      # Join segments
            'path_precision': 3          # Precision for print
        }
        
    async def vectorize(
        self, 
        image: Image.Image,
        config: Optional[dict] = None
    ) -> str:
        """
        Vectorize an image to SVG format
        
        Args:
            image: PIL Image object
            config: Optional custom configuration (overrides defaults)
            
        Returns:
            SVG content as string
        """
        try:
            start_time = time.time()
            
            # Use default config or merge with custom
            vtracer_config = self.default_config.copy()
            if config:
                vtracer_config.update(config)
            
            # Convert image to RGB if needed
            if image.mode == 'RGBA':
                # VTracer works best with RGB
                # Create white background for transparent areas
                rgb_image = Image.new('RGB', image.size, (255, 255, 255))
                rgb_image.paste(image, mask=image.split()[3])  # Use alpha as mask
                image = rgb_image
            elif image.mode != 'RGB':
                image = image.convert('RGB')
            
            # Convert PIL Image to numpy array
            img_array = np.array(image)
            
            # Run VTracer
            logger.info(f"   Vectorizing with VTracer (size: {image.size})...")
            
            svg_content = vtracer.convert_image_to_svg_py(
                img_array,
                colormode=vtracer_config['colormode'],
                hierarchical=vtracer_config['hierarchical'],
                mode=vtracer_config['mode'],
                filter_speckle=vtracer_config['filter_speckle'],
                color_precision=vtracer_config['color_precision'],
                layer_difference=vtracer_config['layer_difference'],
                corner_threshold=vtracer_config['corner_threshold'],
                length_threshold=vtracer_config['length_threshold'],
                splice_threshold=vtracer_config['splice_threshold'],
                path_precision=vtracer_config['path_precision']
            )
            
            process_time = time.time() - start_time
            logger.info(f"   Vectorized in {process_time:.2f}s")
            
            # Add metadata to SVG
            svg_with_metadata = self._add_svg_metadata(svg_content, image.size)
            
            return svg_with_metadata
            
        except Exception as e:
            logger.error(f"❌ Vectorization failed: {str(e)}")
            # Return a simple SVG as fallback
            return self._create_fallback_svg(image)
    
    def _add_svg_metadata(self, svg_content: str, original_size: tuple) -> str:
        """
        Add metadata to SVG content
        
        Args:
            svg_content: Original SVG string
            original_size: (width, height) of original image
            
        Returns:
            SVG with added metadata
        """
        # Add comment with metadata
        metadata = f"""<!-- 
    Generated by PerfectPrint AI
    Vectorizer: VTracer
    Original Size: {original_size[0]}x{original_size[1]}
    Generated: {time.strftime('%Y-%m-%d %H:%M:%S')}
-->
"""
        # Insert after the opening <svg> tag
        if '<svg' in svg_content:
            svg_parts = svg_content.split('>', 1)
            return svg_parts[0] + '>\n' + metadata + svg_parts[1]
        
        return metadata + svg_content
    
    def _create_fallback_svg(self, image: Image.Image) -> str:
        """
        Create a simple fallback SVG if vectorization fails
        
        Args:
            image: PIL Image object
            
        Returns:
            Simple SVG as string
        """
        logger.warning("⚠️  Using fallback SVG (embedded raster image)")
        
        import base64
        import io
        
        # Convert image to base64
        buffered = io.BytesIO()
        image.save(buffered, format="PNG")
        img_base64 = base64.b64encode(buffered.getvalue()).decode()
        
        # Create SVG with embedded image
        width, height = image.size
        svg = f'''<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" 
     xmlns:xlink="http://www.w3.org/1999/xlink"
     width="{width}" 
     height="{height}" 
     viewBox="0 0 {width} {height}">
    <!-- Fallback: Embedded raster image -->
    <image width="{width}" height="{height}" 
           xlink:href="data:image/png;base64,{img_base64}"/>
</svg>'''
        
        return svg
    
    async def vectorize_logo(self, image: Image.Image) -> str:
        """
        Vectorize with settings optimized for logos
        
        Args:
            image: PIL Image object
            
        Returns:
            SVG content as string
        """
        logo_config = {
            'colormode': 'color',
            'hierarchical': 'stacked',
            'mode': 'spline',
            'filter_speckle': 8,         # More aggressive noise removal
            'color_precision': 8,        # Higher color accuracy
            'layer_difference': 8,       # More color layers
            'corner_threshold': 80,      # Sharper corners for logos
            'length_threshold': 2.0,     # Keep smaller details
            'splice_threshold': 30,      # More precise joins
            'path_precision': 4          # Higher precision
        }
        
        return await self.vectorize(image, config=logo_config)
    
    async def vectorize_artwork(self, image: Image.Image) -> str:
        """
        Vectorize with settings optimized for general artwork
        
        Args:
            image: PIL Image object
            
        Returns:
            SVG content as string
        """
        # Use default config (already optimized for artwork)
        return await self.vectorize(image)
    
    def get_service_info(self) -> dict:
        """
        Get information about the vectorizer service
        
        Returns:
            Dictionary with service information
        """
        return {
            "vectorizer": "VTracer",
            "version": "0.6.8",
            "source": "https://github.com/visioncortex/vtracer",
            "license": "MIT",
            "quality": "Matches Adobe Illustrator",
            "typical_speed": "1-3 seconds",
            "supported_modes": ["logo", "artwork", "custom"]
        }


# Create a singleton instance
_vectorizer_service_instance = None

def get_vectorizer_service() -> VectorizerService:
    """
    Get or create the vectorizer service singleton
    
    Returns:
        VectorizerService instance
    """
    global _vectorizer_service_instance
    if _vectorizer_service_instance is None:
        _vectorizer_service_instance = VectorizerService()
    return _vectorizer_service_instance

